'use strict';
const bank=[];for(const mu of [40,45,50,55,60,65])for(const sigma of [8,12,16,20])for(const ratio of [0.125,0.25])for(const roots of [[2,4,6],[3,6,9],[4,8,12]])bank.push({mu,sigma,M:mu+sigma*ratio,ns:roots.map(x=>x*x)});
let scenario=bank[0],studies=[];
function upperTail(z){const t=1/(1+0.2316419*z);return Math.exp(-z*z/2)/Math.sqrt(2*Math.PI)*t*(0.319381530+t*(-0.356563782+t*(1.781477937+t*(-1.821255978+t*1.330274429))));}
function result(n){const se=scenario.sigma/Math.sqrt(n),z=(scenario.M-scenario.mu)/se;return {se,z,p:upperTail(Number(z.toFixed(2)))};}
function checkValue(raw,expected,tolerance){return raw.trim()===''?'blank':Number.isFinite(Number(raw))&&Math.abs(Number(raw)-expected)<tolerance?'correct':'retry';}
function check(){const messages=[];studies.forEach(s=>{const r=result(s.n);['se','z','p'].forEach(key=>{const state=checkValue(document.getElementById(key+s.name).value,r[key],key==='p'?0.000051:0.0051);if(state==='blank')return;messages.push('Study '+s.name+' '+(key==='p'?'probability':key.toUpperCase())+': '+(state==='correct'?'Correct.':key==='se'?'Try σ / √n.':key==='z'?'Try (M − μ) / SE.':'Use the area to the right of your z, written as a decimal.'));});});document.getElementById('feedback').textContent=messages.length?messages.join(' '):'Enter at least one calculation to check.';}
function loadScenario(index){scenario=bank[index];studies=scenario.ns.map((n,i)=>({name:'ABC'[i],n}));const code='L4-'+String(index+1).padStart(3,'0');document.getElementById('scenarioCode').value=code;document.getElementById('scenarioStatus').textContent='Your scenario: '+code+'. Record this ID in your paper.';['mu','sigma','M'].forEach(k=>document.getElementById(k).textContent=scenario[k]);document.getElementById('studyRows').innerHTML=studies.map(s=>'<tr><th scope="row">Study '+s.name+'</th><td>'+scenario.M+'</td><td>'+s.n+'</td>'+['se','z','p'].map(k=>'<td><input id="'+k+s.name+'" type="number" step="'+(k==='p'?'0.0001':'0.01')+'" aria-label="Study '+s.name+' '+(k==='p'?'upper-tail probability':k)+'"></td>').join('')+'</tr>').join('');document.getElementById('study').innerHTML=studies.map((s,i)=>'<option value="'+i+'">Study '+s.name+' · n = '+s.n+'</option>').join('');document.getElementById('study').value='0';document.getElementById('feedback').textContent='';plot();}
function restore(){const code=document.getElementById('scenarioCode').value.trim().toUpperCase(),match=/^L4-(\d{3})$/.exec(code);if(!match||+match[1]<1||+match[1]>bank.length){document.getElementById('scenarioStatus').textContent='Enter a valid scenario ID from L4-001 to L4-'+bank.length+'. Your current studies have not changed.';return;}loadScenario(+match[1]-1);}
function normalTable(){let h='<table><caption>Upper-tail probabilities P(Z ≥ z)</caption><thead><tr><th scope="col">z</th>';for(let c=0;c<10;c++)h+='<th scope="col">.0'+c+'</th>';h+='</tr></thead><tbody>';for(let r=0;r<=34;r++){h+='<tr><th scope="row">'+(r/10).toFixed(1)+'</th>';for(let c=0;c<10;c++)h+='<td>'+upperTail(r/10+c/100).toFixed(4)+'</td>';h+='</tr>';}document.getElementById('normalTable').innerHTML=h+'</tbody></table>';}
function plot(){const s=studies[Number(document.getElementById('study').value)],se=result(s.n).se,wide=result(studies[0].n).se,narrow=result(studies[2].n).se;const x=v=>55+(v-(scenario.mu-4*wide))/(8*wide)*820,y=d=>225-d*(190*narrow*Math.sqrt(2*Math.PI));let points=[];for(let i=0;i<=400;i++){const v=scenario.mu-4*wide+i*8*wide/400,d=Math.exp(-.5*((v-scenario.mu)/se)**2)/(se*Math.sqrt(2*Math.PI));points.push(x(v)+','+y(d));}let svg='<title id="curveTitle">Study '+s.name+' sampling distribution of the mean</title><desc id="curveDesc">Normal distribution centered at the reference population mean for samples of '+s.n+'. The solid line marks the observed sample mean. Larger samples have narrower distributions.</desc><path d="M '+points.join(' L ')+'" fill="none" stroke="#1c8271" stroke-width="3"/>';svg+='<line x1="55" x2="875" y1="225" y2="225" stroke="#8999ae"/>';for(let v=scenario.mu-4*wide;v<=scenario.mu+4*wide+0.001;v+=wide)svg+='<text x="'+x(v)+'" y="248" text-anchor="middle">'+Number(v.toFixed(2))+'</text>';[scenario.mu,scenario.M].forEach(v=>{svg+='<line x1="'+x(v)+'" x2="'+x(v)+'" y1="20" y2="225" stroke="'+(v===scenario.mu?'#192f52':'#b24032')+'" '+(v===scenario.mu?'stroke-dasharray="5 4"':'')+'/><text x="'+(x(v)+7)+'" y="18">'+(v===scenario.mu?'μ = '+scenario.mu:'M = '+scenario.M)+'</text>';});let tail=[];for(let i=0;i<=160;i++){let v=scenario.M+(scenario.mu+4*wide-scenario.M)*i/160;tail.push(x(v)+','+y(Math.exp(-.5*((v-scenario.mu)/se)**2)/(se*Math.sqrt(2*Math.PI))));}svg+='<path d="M '+x(scenario.M)+',225 L '+tail.join(' L ')+' L '+x(scenario.mu+4*wide)+',225 Z" fill="#b24032" opacity="0.22"/>';document.getElementById('curve').innerHTML=svg;}

if(typeof document!=='undefined'){document.getElementById('check').onclick=check;document.getElementById('study').onchange=plot;document.getElementById('generate').onclick=()=>{let i=Math.floor(Math.random()*(bank.length-1));const current=bank.indexOf(scenario);if(i>=current)i++;loadScenario(i);};document.getElementById('restore').onclick=restore;normalTable();loadScenario(Math.floor(Math.random()*bank.length));}
